@startuml
!pragma layout smetana
'https://plantuml.com/sequence-diagram

object Main
object User
object Order
object Orderline
object toppings
object bottoms

Main *-- User
Main *-- Order

Order *-- Orderline
User *-- Orderline

Orderline *-- toppings
Orderline *-- bottoms
@enduml